#!/usr/bin/env bash
# Container entrypoint: source the ROS environment and any built overlay, then
# hand off. Sourcing here rather than in .bashrc means non-interactive commands
# (CI, `docker compose run`) get the same environment as an interactive shell.
set -e

# shellcheck disable=SC1090,SC1091  # provided by the ROS installation at runtime
source "/opt/ros/${ROS_DISTRO}/setup.bash"

# Overlay from a previous build, if one exists. Absent on a first run.
if [ -f /workspace/workspace/install/setup.bash ]; then
    # shellcheck disable=SC1091  # generated by colcon at build time
    source /workspace/workspace/install/setup.bash
fi

# Host-agnostic Python tooling.
if [ -d "${CITE_VENV}" ]; then
    export PATH="${CITE_VENV}/bin:${PATH}"
fi

exec "$@"
