#!/usr/bin/env bash
# Container entrypoint: source the ROS environment and any built overlay, then
# hand off. Sourcing here rather than in .bashrc means non-interactive commands
# (CI, `docker compose run`) get the same environment as an interactive shell.
set -e

# shellcheck disable=SC1090,SC1091  # provided by the ROS installation at runtime
source "/opt/ros/${ROS_DISTRO}/setup.bash"

# Overlay from a previous build, if one exists. Absent on a first run.
if [ -f /workspace/workspace/install/setup.bash ]; then
    # shellcheck disable=SC1091  # generated by colcon at build time
    source /workspace/workspace/install/setup.bash
fi

# The host-agnostic Python tooling deliberately stays OFF the PATH.
#
# Putting ${CITE_VENV}/bin first makes its `python3` the default, and that
# interpreter has none of the ROS Python packages — so every ament/colcon build
# dies with "No module named 'catkin_pkg'", which reads as a broken ROS
# installation rather than as a shadowed interpreter. The two environments are
# separate on purpose (requirements/README.md): ROS Python comes from apt, the
# tooling venv comes from pip, and neither may mask the other.
#
# Scripts that need the tooling resolve it explicitly through cite_venv_bin in
# scripts/_lib.sh. CITE_VENV is exported by the image for them to find.

exec "$@"
