"""The derived-asset half of ``assets/manifest.yaml``.

ADR-0012 makes the manifest the one place an asset's provenance lives, and is
blunt about the weakness that buys: *"the manifest is only as good as the
discipline behind it. An asset used in a scene but absent from `manifest.yaml` is
unreproducible, and nothing outside code review will catch it."* ADR-0028 adds a
second kind of asset — one **derived** from a pinned vendor file rather than
captured — and requires its provenance and checksums in the same file.

So this module does not add a second manifest. It owns one delimited region of
the existing one, rewritten whole by ``./scripts/hulls --write`` and compared by
``./scripts/hulls`` with no flag -- checking is the default and there is no
``--check`` to pass, which this sentence invented. Everything outside the markers — the header, the
policy comments, the ``assets:`` list the fetcher reads — is preserved byte for
byte.

**Why a generated region rather than a hand-written table.** Every declared mesh
contributes two checksums, a byte count and two triangle counts. A person
maintaining those by hand is a person who will one day update a mesh and not the
digest beside it, which is the failure ADR-0012 already names, made worse by being
invisible. A person maintaining them by hand is also not what ADR-0012 asked for:
it asked for provenance to *exist*, and a generated region that a check can
falsify is stronger discipline than a hand-written one that nothing verifies.

*(This paragraph said "sixty-odd checksums" until 2026-08-31 and the region held
twenty-six. A count of a generated collection stated in prose is a number that goes
stale the first time the collection changes — ADR-0027's correction says so in as
many words — so it is a rate here and the count comes from ``./scripts/hulls``.)*

**And the argument above is only true because something runs.** It was not, when it
was written: ``cite-model hulls`` was invoked by no script, no CI step and no test,
and three fields of the region — ``source.version``, ``bytes`` and ``installed_as``
— could each be mutated into a well-formed lie with the whole suite green. The
check form is now a step in ``./scripts/lint`` wherever the vendor source is
imported, and ``tools/tests/test_manifest_region.py`` binds those three fields to
what they describe on any host.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

BEGIN = "# --- BEGIN derived assets: generated by `cite-model hulls --write`, do not hand-edit ---"
END = "# --- END derived assets ---"


class ManifestError(Exception):
    """The manifest is missing its markers, or carries them in the wrong order."""


@dataclass(frozen=True)
class Region:
    """The manifest, split at the markers so the region can be replaced."""

    before: str
    body: str
    after: str


def split(text: str) -> Region:
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0 or stop < start:
        raise ManifestError(f"assets/manifest.yaml must carry {BEGIN!r} and {END!r}, in that order")
    return Region(
        before=text[: start + len(BEGIN)],
        body=text[start + len(BEGIN) : stop],
        after=text[stop:],
    )


def render(entries: list[dict]) -> str:
    """The region body for a list of derived-asset entries.

    ``sort_keys=False`` so the fields read in the order a person would want them —
    what it is, then where it came from, then what it hashes to — rather than
    alphabetically, which would put ``sha256`` before ``source``.
    """
    dumped = yaml.safe_dump(
        {"derived": entries}, sort_keys=False, default_flow_style=False, width=100
    )
    return "\n" + dumped


def replace(text: str, entries: list[dict]) -> str:
    region = split(text)
    return region.before + render(entries) + region.after


def read(path: Path) -> list[dict]:
    """The derived entries currently recorded, or an empty list."""
    doc = yaml.safe_load(path.read_text()) or {}
    return list(doc.get("derived") or [])
