"""The one Jinja2 environment, configured for determinism and loud failure.

Two settings here are load-bearing rather than stylistic.

``StrictUndefined``: a mistyped variable in a template must be an error. With
Jinja's default an undefined name renders as the empty string, which produces a
*syntactically valid* SDF with a missing pose — a generated artifact that loads
cleanly and places something at the origin. That is the silently-wrong-value
failure this whole layer exists to prevent, and it would be introduced by the
tool meant to prevent it.

``keep_trailing_newline`` and the fixed float filter: byte-identical output on
repeated runs is required by ADR-0004, because the hand-edit check compares a
committed artifact against a fresh run.
"""

from __future__ import annotations

from collections.abc import Iterable
from xml.sax.saxutils import escape, quoteattr

from jinja2 import Environment, PackageLoader, StrictUndefined

from cite_tools.model.units import fmt, fmt_float, fmt_triple

#: Header stamped into every generated artifact. It names the command that
#: regenerates the file, because the most useful thing a generated file can tell
#: whoever opened it to edit is how to make the change properly instead.
BANNER_LINES = (
    "GENERATED by cite-model. DO NOT EDIT.",
    "Source:     model/",
    "Regenerate: ./scripts/validate-model --write",
    "A hand edit here is a Critical review finding (ADR-0004) and is detected by",
    "./scripts/validate-model, which diffs this tree against a fresh generator run.",
)

#: XML forbids `--` inside a comment, so the banner above cannot be used verbatim
#: in a URDF or an SDF: `--write` makes the document not well-formed, and xacro
#: reports it as a parse error at a column in the banner rather than as anything
#: to do with the flag. The wording differs here for that reason alone.
XML_BANNER_LINES = (
    "GENERATED by cite-model. DO NOT EDIT.",
    "Source:     model/",
    "Regenerate: ./scripts/validate-model, passing the write flag.",
    "A hand edit here is a Critical review finding (ADR-0004) and is detected by",
    "./scripts/validate-model, which diffs this tree against a fresh generator run.",
)


def xml_banner() -> str:
    assert not any("--" in line for line in XML_BANNER_LINES), "XML comments cannot contain '--'"
    body = "\n     ".join(XML_BANNER_LINES)
    return f"<!-- {body} -->"


def hash_banner() -> str:
    return "\n".join(f"# {line}" for line in BANNER_LINES)


def environment() -> Environment:
    env = Environment(
        loader=PackageLoader("cite_tools", "templates"),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["m"] = fmt
    # `f` where the output is read back as a ROS parameter and the type matters.
    env.filters["f"] = fmt_float
    env.filters["triple"] = _triple
    env.filters["xml"] = escape
    env.filters["attr"] = quoteattr
    env.globals["xml_banner"] = xml_banner
    env.globals["hash_banner"] = hash_banner
    return env


def _triple(values: Iterable[float]) -> str:
    return fmt_triple(values)
