"""The one Jinja2 environment, configured for determinism and loud failure.

Two settings here are load-bearing rather than stylistic.

``StrictUndefined``: a mistyped variable in a template must be an error. With
Jinja's default an undefined name renders as the empty string, which produces a
*syntactically valid* SDF with a missing pose — a generated artifact that loads
cleanly and places something at the origin. That is the silently-wrong-value
failure this whole layer exists to prevent, and it would be introduced by the
tool meant to prevent it.

``keep_trailing_newline`` and the fixed float filter: byte-identical output on
repeated runs is required by ADR-0004, because the hand-edit check compares a
committed artifact against a fresh run.
"""

from __future__ import annotations

from collections.abc import Iterable
from xml.sax.saxutils import escape, quoteattr

from jinja2 import Environment, PackageLoader, StrictUndefined

from cite_tools.model.units import fmt, fmt_float, fmt_triple

#: Header stamped into every generated artifact. It names the command that
#: regenerates the file, because the most useful thing a generated file can tell
#: whoever opened it to edit is how to make the change properly instead.
BANNER_LINES = (
    "GENERATED by cite-model. DO NOT EDIT.",
    "Source:     model/",
    "Regenerate: ./scripts/validate-model --write",
    "A hand edit here is a Critical review finding (ADR-0004) and is detected by",
    "./scripts/validate-model, which diffs this tree against a fresh generator run.",
)

#: XML forbids `--` inside a comment, so the banner above cannot be used verbatim
#: in a URDF or an SDF: `--write` makes the document not well-formed, and xacro
#: reports it as a parse error at a column in the banner rather than as anything
#: to do with the flag. The wording differs here for that reason alone.
XML_BANNER_LINES = (
    "GENERATED by cite-model. DO NOT EDIT.",
    "Source:     model/",
    "Regenerate: ./scripts/validate-model, passing the write flag.",
    "A hand edit here is a Critical review finding (ADR-0004) and is detected by",
    "./scripts/validate-model, which diffs this tree against a fresh generator run.",
)


def xml_banner() -> str:
    assert not any("--" in line for line in XML_BANNER_LINES), "XML comments cannot contain '--'"
    body = "\n     ".join(XML_BANNER_LINES)
    return f"<!-- {body} -->"


def hash_banner() -> str:
    return "\n".join(f"# {line}" for line in BANNER_LINES)


def environment() -> Environment:
    env = Environment(
        loader=PackageLoader("cite_tools", "templates"),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["m"] = fmt
    # `f` where the output is read back as a ROS parameter and the type matters.
    env.filters["f"] = fmt_float
    env.filters["triple"] = _triple
    # For a boolean a safety gate decides on. See `_declared_bool`.
    env.filters["declared_bool"] = _declared_bool
    env.filters["xml"] = escape
    env.filters["attr"] = quoteattr
    env.globals["xml_banner"] = xml_banner
    env.globals["hash_banner"] = hash_banner
    return env


def _triple(values: Iterable[float]) -> str:
    return fmt_triple(values)


def _declared_bool(value: object) -> str:
    """Render a REQUIRED boolean, refusing anything that is not one.

    `StrictUndefined` above catches a name a template never received. It does
    not catch a name that arrived carrying `None`, and the ordinary Jinja
    spelling of a boolean — `{{ 'true' if x else 'false' }}` — renders that as
    `false` in silence.

    For most fields that is harmless. For a field a hardware gate decides on it
    is the exact defect ADR-0054 exists to close, at the last hop: that record
    makes `commands_physical_hardware` required with NO DEFAULT precisely because
    a hardware path must never be reachable by omission, and a template that
    turns an unset value into `false` reintroduces the default the schema
    refused. Nothing is believed to pass `None` today; the point is that the
    template would not say so if it did.

    A `TypeError` and not a warning, so the generator stops with the value it was
    given rather than writing an artifact that reads as a decision somebody made.

    **AND A `TypeError` AND NOT `PlanningConfigurationError`, WHICH IS A DECIDED
    CHOICE AND NOT AN OVERSIGHT.** `cli.py::_generate` catches the latter so that
    a MODEL problem prints as `error <rule> <where>` rather than as a tool that
    crashed, and this raise is deliberately outside that: what it guards is a
    GENERATOR INVARIANT, not a model statement, so a traceback naming this
    function is the honest report. Checked rather than assumed, on 2026-09-10:

    - The value cannot arrive from L0. `HardwareBackend.commands_physical_hardware`
      is a required `bool` on a pydantic model, so a non-boolean written in the
      model is refused at LOAD and reported by the loader as a model finding; it
      never reaches a template.
    - The one way a non-boolean does arrive is this module's sibling generator
      contradicting itself — `counterpart_commands_physical_hardware` is
      `bool | None`, and `plan.yaml.j2` renders it only inside
      `{% if manager.counterpart_backend %}`, so `None` here means
      `generate/bringup.py` set a counterpart backend without the fact that goes
      with it. That is a bug in `tools/`, and giving it the finding shape would
      send its reader to `model/` to look for it.
    - A traceback out of the generator is not exceptional either: `ResolveError`
      from `model/resolve.py` reaches the CLI the same way, uncaught.

    If a future change makes this value reachable from something a model author
    writes, that inverts: it then needs the finding shape, and this list is the
    thing to re-read.
    """
    if not isinstance(value, bool):
        raise TypeError(
            f"declared_bool received {value!r} ({type(value).__name__}); this "
            "field is required and has no default, so there is no value to fall "
            "back to. Rendering it as `false` would make a hardware path "
            "reachable by omission (ADR-0054)."
        )
    return "true" if value else "false"
